### ISSUE TITLE
Unable to figure out how to map shortcut to script.

### ISSUE THREAD

**Issue by pnjsinc** [oleg-shilo/scripts.npp#3]
I see in the top of the script that is created, npp_shortcut Ctrl+Alt+Shift+F10'...
However I am not following how to make use of this.

Any help would be greatly appreciated.

**Comment by oleg-shilo** [comment]
If you have a script with `//npp_shortcut Ctrl+F11` instruction on top presnt in the `C:\Users\oleg.shilo\Documents\NppScripts` then the plugin will load this script at N++ startup and bind it to the `Ctrl+F11` shortcut.

So when you hit the key combination the script will be executed.

**Comment by pnjsinc** [comment]
Greetings Oleg, I have added the lines as you stated just under  the //css_ref section
//css_ref C:\Program Files\Notepad++\plugins\NppScripts\NppScripts.dll
//css_ref C:\Program Files\Notepad++\plugins\NppScripts\NppScripts\NppScripts.asm.dll
//npp_shortcut Ctrl+Shift+F10

The files exist in my users\Documents\NppScripts folder, I have restarted N++, however still does not recognize the shortcut.

Anything I am mising?

**Comment by oleg-shilo** [comment]
Not sure, I would suggest you use the samples that come with the plugin as they are verified to work. 
This way you can check if there is something unusual about your environment or with your script.
The easiest sample for testing is the "Format XML"

![npp_automation](https://user-images.githubusercontent.com/16729806/93212894-8d91dd00-f7a6-11ea-9313-b0ab9ea77cd9.gif)

If you need to restore the missing or damaged samples you can always restore them from the plugin about box:

![image](https://user-images.githubusercontent.com/16729806/93578042-28293080-f9e0-11ea-88e7-31e9062b13d7.png)

**Comment by pnjsinc** [comment]
Just wanted to let you know, I did not check to see if there was conflicts, this is what it came down to.
Thanks for your help.
