### ISSUE TITLE
[question] Feasibility of writing a particular Npp script

### ISSUE THREAD

**Issue by pa-0** [oleg-shilo/scripts.npp#6]
Hi oleg,

How difficult would it be for a beginner like me (who's been coding as a hobby for a few months) to write a script that doesn't necessarily imitate the files.associations setting's functionality, but rather just arrives at the same result?

### _From VS Code's documentation_: 
***
[Can I map additional file extensions to a language?](https://code.visualstudio.com/docs/languages/overview#_can-i-map-additional-file-extensions-to-a-language)
Yes, with the files.associations [setting](https://code.visualstudio.com/docs/getstarted/settings) you can map file extensions to an existing language either globally or per workspace.
Here is an example that will associate more file extensions to the PHP language:
`"files.associations": {`
`    "*.php4": "php",     `
`    "*.php5": "php"      `
`}                      `
You can also configure full file paths to languages if needed. The following example associates all files in a folder somefolder to PHP:
`"files.associations": {       `
`    "**/somefolder/*.*": "php"`
`}                             `
Note that the pattern is a [glob pattern](https://code.visualstudio.com/docs/editor/glob-patterns) that will match on the full path of the file if it contains a / and will match on the file name otherwise.
***
So using the documentation as reference, I have a directory with code files in subfolders categorized by language: `cpp\`, `java\`, `cs\`,  etc. and despite the fact that all of these scripts have filenames **lacking extensions**, they are formatted correctly when opened in vs code using settings modeled after the example glob pattern above like so:
`"files.associations": {`
`    "**/cpp/*.*": "cpp"`
`}                      `

Would I be getting in way over my head trying to write a script for npp that results in automatic language selection under the same conditions? Thanks in advance.

**Comment by oleg-shilo** [comment]
I cannot be sure, but it seems to me that it is possible.

Ideally you can subscribe for the FileOpen notification. But I am not sure if I opened it to the users.
Thus the simplest way is to run a background monitoring thread where you check the file name of the currently selected tam/doc and if you detect that it is not what you need then you call `SetCurrentLanguage`:



```C#
using NppScripts;

public class Script : NppScript
{
    public override void Run()
    {
        try
        {
            Task.Run(() =>
            {
                Thread.Sleep(1000);
                string path;
                Npp.Editor.SendMessage(NppMsg.NPPM_GETFILENAME, 0, out path);

                if (path.EndsWith(".py"))
                    Npp.Editor.SetCurrentLanguage(LangType.L_PYTHON);
            });
        }
        catch (Exception e)
        {
            Plugin.Output.Clear();
            Plugin.Output.WriteLine("'Format XML Document' Error:\r\n" + e.Message);
        }
    }
}
```

The code above will work but ideally, you want to set language not every second but only if it is a new document. so you may want to keep the history of the files that you have already set the language to your custom value.

**Comment by pa-0** [comment]
This is super helpful.  Much appreciated!

**Comment by oleg-shilo** [comment]
Note that `LangType` lists only a handful of languages. Much less than NPP supports. so you will need to find from the NPP documentation what are the values of other languages that you might need. The are just integers so you will be able to pass them as a number, not the name of the lang. Python is just happens to be already there so I used it as an example.

**Comment by pa-0** [comment]
Noted. Many thanks.
